### ISSUE TITLE
How to finetune on generic seq2seq task apart from NMT?

### ISSUE THREAD

**Issue by arijitx** [AI4Bharat/indic-bart#1]

**Comment by prajdabre** [comment]
Hi,
There's a training command for summarisation in the readme. 
Following that command the precise answer your question is: simply pass the train/dev files for your task via the train_src, train_tgt, dev_src and dev_tgt arguments and then set the appropriate hyperparameters.

If you can give me a clearer idea of your task then I can help you better. :)

**Comment by arijitx** [comment]
Thanks @prajdabre this answers my question, seems like I overlooked that part
