### ISSUE TITLE
Doubt: Where is the final model checkpoint(for all languages combined) saved for multilingual training?

### ISSUE THREAD

**Issue by ShivprasadSagare** [AI4Bharat/indic-bart#10]
Hi, I had a doubt about the training process.

After running the training on (hi, en) and (bn, en) pairs at the same time, I can see the respective model checkpoints, for e.g. model.ft.best_dev_bleu.hi-en. I wish to ask if two separate models are trained for 2 languages passed, or is it the same multilingual model that is trained, and the checkpoints are stored for different languages based on individual dev BLEU? In the later case, where is the combined model checkpoint for all langs saved, if at all it is saved? Is it model.ft? Or is it in model.ft_deploy directory?

Thank you in advance.

**Comment by prajdabre** [comment]
The model with "global" in its name. This is also the model in the model.ft_deploy folder

**Comment by ShivprasadSagare** [comment]
Thank you so much.
