### ISSUE TITLE
Summarization does not return a summary using the pretrained model

### ISSUE THREAD

**Issue by Ayush1702** [AI4Bharat/indic-bart#11]
```python
from transformers import AutoTokenizer, AlbertTokenizer
from transformers import AutoModelForSeq2SeqLM, MBartForConditionalGeneration

model = MBartForConditionalGeneration.from_pretrained('/content/IndicBART')
tokenizer = AlbertTokenizer.from_pretrained('/content/IndicBART')

marathi_text_sample = """
काल रात्री मी जे काही पाहिलं ते एका कलाकाराने दिलेले तेजस्वी सुख होतं. तू ज्या पद्धतीने चंद्रमुखी साकारली आहेस, ती मनाचा खोलवर ठाव घेणारी आहे. एक प्रेक्षक म्हणून मी त्यावेळी त्या चंद्रमुखीच्या प्रेमात पडलो. त्याक्षणी मला तिला माझ्यासोबत घेऊन जावंस वाटलं. तिचे संरक्षण करावंस वाटलं.
मला त्यावेळी तिच्यातील वेदना जाणवल्या आणि मी तिच्यातील एक भाग आहे, असंही क्षणार्धात मला वाटलं. मनाचा घाव घेणारी, निष्पाप, खोलवर जखम झालेली असली तरीही तिचे शुद्ध अंतकरण पाहून मी भरुन पावलो आहे. तिच्या प्रवासाचे साक्षीदार झालेल्या सर्वांनाच तिने मोहिनी घातली आहे.
अमृता तुझ्या माध्यमातून तू आम्हा सर्वांना चंद्रमुखीच्या प्रवासाचे साक्षीदार बनवल्याबद्दल तुझे धन्यवाद.
कलाकाराच्या आयुष्यात वेगवेगळ्या टप्प्यावर येणारी प्रत्येक भूमिका ही एका खास हेतूसाठी येते आणि तो हेतू म्हणजे पुन्हा स्वत:शीच कनेक्ट होणे. कलाकार करत असलेली प्रत्येक भूमिका ही त्याच्या आत्मावर खोलवर ठसा उमटवते. चंद्रमुखी ही तुझ्यासाठी तेच करेल.
या प्रवासात तुला स्वत:चा खरा शोध घेण्यासाठी, पुढे जाण्यासाठी आणि पुन्हा मागच्या गोष्टींसोबत रि-कनेक्ट होण्यासाठी नक्कीच मदत करतील. अमृता मी तुझ्यासाठी खूप आनंदी आहे आणि मला तुझा खूप अभिमान वाटतो.
"""

inputs = tokenizer.encode(marathi_text_sample, return_tensors="pt", padding=True)

# summarize
generated_ids = model.generate(inputs, min_length=30, max_length=70, no_repeat_ngram_size=2, num_beams=4, early_stopping=True)

# generate summary
tokenizer.decode(generated_ids[0], skip_special_tokens=True)
```

I have been trying to perform summarization task on a Marathi text using the above piece of code as an example, however, the generated summary is simply the first couple lines of the input text.
Is there something I'm missing, I have tried passing "summarize: " at the beginning like done in MBart but no results.

**Comment by prajdabre** [comment]
Are you using the pre-trained model: "https://huggingface.co/ai4bharat/IndicBART"?

This model needs to be fine-tuned for summarization. Using it as it is won't work as it is not trained for summarization.

Try this model: https://huggingface.co/ai4bharat/MultiIndicHeadlineGeneration

I does headline generation but the principle is the same. Fine tune IndicBART on summarization data as in the IndicBART paper.

**Comment by Ayush1702** [comment]
Okay, In that case I'm trying to perform finetuning on colab, what would be colab-friendly-finetuning parameters to avoid CUDA out of memory errors?

**Comment by prajdabre** [comment]
I suggest you wait for a bit.

We are in the process of uploading a model fine tuned on XL-SUM here: https://huggingface.co/ai4bharat/IndicBART-XLSum

Keep checking it in the next 24 hours to see if a model has been uploaded!

**Comment by prajdabre** [comment]
@Ayush1702 Check https://huggingface.co/ai4bharat/IndicBART-XLSum

You can use it for summarization now!

**Comment by Ayush1702** [comment]
Thanks a lot @prajdabre, I did test it out and it works fine!
Would be even more helpful if you can share finetuning steps for low resource computation like colab for Marathi, and other languages.
This will do for now :)

**Comment by prajdabre** [comment]
Ezzzz! Just look here https://github.com/AI4Bharat/indic-bart
