### ISSUE TITLE
Difference between IndicBARTSS and IndicBART-XLSum?

### ISSUE THREAD

**Issue by varadhbhatnagar** [AI4Bharat/indic-bart#12]
With reference to the model cards on HuggingFace for `ai4bharat/IndicBARTSS`  and `ai4bharat/IndicBART-XLSum`, other than support for additional Indic languages, is there any difference between the two? 

`IndicBART-XLSum` training has been detailed in the IndicBART paper[https://arxiv.org/abs/2109.02903]. Is there any literature detailing the `IndicBARTSS` training?

**Comment by prajdabre** [comment]
Indicbartss is a pretrained model which needs to be fine tuned for downstream tasks like summarisation, machine translation.

Indicbart-xlsum is a fine tuned model for summarisation for 7 languages.

One is a pretrained model which doesn't serve any purpose by itself. The other is a fine tuned model which does summarisation.

Indicbartss is the same as IndicBart except the former uses the original language script and the latter uses devanagari script. In the case of the latter the original language script is mapped to devanagari. All of this is described in our ACL paper: https://aclanthology.org/2022.findings-acl.145/

I should really update the arxiv paper :/

**Comment by varadhbhatnagar** [comment]
Understood. Thanks a lot! Are you aware of any notebooks which fine-tune these models using the `Seq2SeqTrainer` on HF?

**Comment by prajdabre** [comment]
> Understood. Thanks a lot! Are you aware of any notebooks which fine-tune these models using the `Seq2SeqTrainer` on HF?

No but just use YANMTT which does essentially the same thing you asked.
