### ISSUE TITLE
how can we finetune indicbart pre-trained other than specified language.? 

### ISSUE THREAD

**Issue by Aniruddha-JU** [AI4Bharat/indic-bart#13]
Actually when I fine-tune it for other language, it is getting
RuntimeError: The expanded size of the tensor (20) must match the existing size (17) at non-singleton dimension 1.  Target sizes: [3, 20, 1].  Tensor sizes: [3, 17, 1]

**Comment by Aniruddha-JU** [comment]
I understand the language identifier special token is not in the vocabulary list. So can we do that in any other way?

**Comment by prajdabre** [comment]
If your language is not in IndicBART then you can use any language identifier from the current set of language identifiers. <2hi> should be fine. If you know which language is the most similar to your language, then you can use that language's identifier.
