### ISSUE TITLE
How to fine-tune the model for summarization, if we want to train the model with more than one languges

### ISSUE THREAD

**Issue by Aniruddha-JU** [AI4Bharat/indic-bart#2]
I want to mix English and Hind Summarization data, then how can I pass the language code here?

**Comment by prajdabre** [comment]
If you look at the example for translation, multiple languages should be separated by a comma and corresponding files should also be separated by a comma.

Example: --train_slang hi,en --train_tlang hi,en --train_src train.doc.hi,train.doc.en --train_tgt train.sum.hi,train.sum.en

Hope this helps.

**Comment by Aniruddha-JU** [comment]
After training, a few models are saving based dev data, which model should we use? is it model.ft.best_dev_bleu.global model?

**Comment by prajdabre** [comment]
If you train on one language then that's the checkpoint. If you train on multiple languages there are checkpoints with suffixes like $lang-$lang instead of global.

**Comment by Aniruddha-JU** [comment]
Hi, I am getting this error, during fine-tune
RuntimeError: The expanded size of the tensor (25) must match the existing size (19) at non-singleton dimension 1.  Target sizes: [5, 25, 1].  Tensor sizes: [5, 19, 1]

**Comment by Aniruddha-JU** [comment]
I did not pass any padding argument.

**Comment by prajdabre** [comment]
I'm not sure what you mean by padding argument but please tell me what training command you used.

**Comment by Aniruddha-JU** [comment]
python train_nmt.py --train_slang en,bn --train_tlang en.bn --dev_slang en,bn --dev_tlang en,bn     --train_src eng_pa_train.txt,ben_pa_train.txt --train_tgt eng_q_train.txt,ben_q_train.txt --dev_src eng_pa_dev.txt,ben_pa_dev.txt     --dev_tgt eng_q_dev.txt,ben_q_dev.txt --model_path model.ft --encoder_layers 6 --decoder_layers 6     --label_smoothing 0.1 --dropout 0.1 --attention_dropout 0.1 --activation_dropout 0.1     --encoder_attention_heads 16 --decoder_attention_heads 16 --encoder_ffn_dim 4096     --decoder_ffn_dim 4096 --d_model 1024 --tokenizer_name_or_path albert-indicunified64k     --warmup_steps 16000 --weight_decay 0.00001 --lr 0.0003 --max_gradient_clip_value 1.0     --dev_batch_size 128 --port 22222 --shard_files --hard_truncate_length 512     --pretrained_model indicbart_model.ckpt --max_src_length 384 --max_tgt_length 64     --is_summarization --dev_batch_size 64 --max_decode_length_multiplier -60     --min_decode_length_multiplier -10 --no_repeat_ngram_size 4 --length_penalty 1.0

**Comment by Aniruddha-JU** [comment]
Decoding batch from a pool of 2390 examples
Decoding batch from a pool of 2390 examples
Decoding batch from a pool of 2390 examples
Decoding batch from a pool of 2390 examples
Decoding batch from a pool of 2390 examples
Decoding batch from a pool of 2390 examples
Decoding batch from a pool of 2390 examples
Decoding batch from a pool of 2390 examples
Decoding batch from a pool of 2390 examples
Decoding batch from a pool of 2390 examples
Decoding batch from a pool of 2390 examples
BLEU score using sacrebleu after 0 iterations is 0.12502507501778454 for language pair bn-bn
New peak reached for bn-bn . Saving.
Global BLEU score using sacrebleu after 0 iterations is: 0.817187447220241
New peak reached. Saving.
Saving the model
Loading from checkpoint
/home/aniruddha/yanmtt/py36/lib/python3.6/site-packages/torch/optim/lr_scheduler.py:234: UserWarning: Please also save or load the state of the optimizer when saving or loading the scheduler.
  warnings.warn(SAVE_STATE_WARNING, UserWarning)
Traceback (most recent call last):
  File "train_nmt.py", line 859, in <module>
    run_demo()
  File "train_nmt.py", line 856, in run_demo
    mp.spawn(model_create_load_run_save, nprocs=args.gpus, args=(args,train_files, dev_files, quit_condition))         #
  File "/home/aniruddha/yanmtt/py36/lib/python3.6/site-packages/torch/multiprocessing/spawn.py", line 199, in spawn
    return start_processes(fn, args, nprocs, join, daemon, start_method='spawn')
  File "/home/aniruddha/yanmtt/py36/lib/python3.6/site-packages/torch/multiprocessing/spawn.py", line 157, in start_processes
    while not context.join():
  File "/home/aniruddha/yanmtt/py36/lib/python3.6/site-packages/torch/multiprocessing/spawn.py", line 118, in join
    raise Exception(msg)
Exception:

-- Process 0 terminated with the following error:
Traceback (most recent call last):
  File "/home/aniruddha/yanmtt/py36/lib/python3.6/site-packages/torch/multiprocessing/spawn.py", line 19, in _wrap
    fn(i, *args)
  File "/home/aniruddha/yanmtt/train_nmt.py", line 488, in model_create_load_run_save
    lprobs, labels, args.label_smoothing, ignore_index=tok.pad_token_id
  File "/home/aniruddha/yanmtt/common_utils.py", line 82, in label_smoothed_nll_loss
    smooth_loss.masked_fill_(pad_mask, 0.0)
RuntimeError: The expanded size of the tensor (24) must match the existing size (18) at non-singleton dimension 1.  Target sizes: [8, 24, 1].  Tensor sizes: [8, 18, 1]

**Comment by prajdabre** [comment]
Hi

The problem is in your command.

You used: --train_tlang en.bn
You should use: --train_tlang en,bn

The comma is the issue.

**Comment by Aniruddha-JU** [comment]
Thank you, problem is solved:

One more query is that, if we use it as cross-lingual training.. (I mean train with english and bengali) and evaluate it on another languages) then  should we use global models model.ft.best_dev_bleu.global mode

**Comment by prajdabre** [comment]
That's an open question so I'm not sure.
