### ISSUE TITLE
Duplicate file name in sample data section for finetuning for NMT

### ISSUE THREAD

**Issue by ShivprasadSagare** [AI4Bharat/indic-bart#4]
train.en-hi.hi file name is repeated, whereas one of it should be train.en-hi.en. The inherent links are correct though and download correct files for both hi and en.

**Comment by ratishsp** [comment]
Hi @ShivprasadSagare,
Thanks for the issue. Could you create a PR fixing the issue. We will be happy to merge.

**Comment by ShivprasadSagare** [comment]
Sure @ratishsp, done. Excuse me for the delay.
