### ISSUE TITLE
File downloads are not accessible

### ISSUE THREAD

**Issue by ThanmayJ** [AI4Bharat/indic-bart#6]
Hello,
The files hosted on GCP seem to be down again for about a week now.
Is there any other way we can download the models and tokenizers (possibly a temporary GDrive link, like the one shared for https://github.com/AI4Bharat/indicTrans/issues/31#issuecomment-1005398241) ?

**Comment by prajdabre** [comment]
It's hosted on huggingface too 

https://huggingface.co/ai4bharat/IndicBART

Get the model and save it locally via model.save_pretrained('folder') 

Then the checkpoint is available as pytorch.bin in that folder.

Hope it works.

**Comment by ThanmayJ** [comment]
Thanks!

I was specifically looking for the non-unified script models, but I suppose this works for now.

Instead of the albert-indicunified64k tokenizer model and vocab, will spiece.model and spiece.vocab from [IndicBERT](https://huggingface.co/ai4bharat/indic-bert/tree/main) (non-unified) serve the purpose?

IndicBERT has a vocabulary of 200k though, so I'm guessing I may have to edit the added_tokens.json first.

**Comment by prajdabre** [comment]
IndicBart and indicbert vocabs are different. You will have to use the official tokenizer on huggingface I mentioned. For that you will end up having to use script mapping to devanagari using indicnlp library. Sorry for the mess. I'll tell the ai4b people I know about the gcp issues.

**Comment by ThanmayJ** [comment]
No problem, will use script mapping then

Thanks a lot!

**Comment by ThanmayJ** [comment]
The downloads are accessible again, for anyone who faced the same issue.
