### ISSUE TITLE
Import error while running decoding_nmt.py

### ISSUE THREAD

**Issue by ShivprasadSagare** [AI4Bharat/indic-bart#9]
I have installed all the prerequisites as stated in the README. I have also installed transformers(4.3.2) using the modified code made available in yanmtt repo. Following error occurs on running the decoding command as stated here https://github.com/AI4Bharat/indic-bart#decoding-command
```
Traceback (most recent call last):
  File "decode_nmt.py", line 34, in <module>
    from transformers import AutoTokenizer, MBartTokenizer, MBart50Tokenizer, BartTokenizer, AlbertTokenizer
ImportError: cannot import name 'MBart50Tokenizer'
```

**Comment by prajdabre** [comment]
You have to first uninstall any existing transformers installation. If you dont do that then even if you try to install from my repo, it wont override the previous transformers installation.

What is the output of: 
import transformers
print(transformers.__path__)

**Comment by ShivprasadSagare** [comment]
Worked. I uninstalled all installations of transformers, and then reinstalled your local code. It resolved the error. Thank you.
